name: LINE Notify example
on:
  issues:
    types: opened
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: jatu-studiobox/github-actions-line-notify@v1.0
        with:
          access_token: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
          repository_name: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
          issue_title: ${{ github.event.issue.title }}
          issue_html_url: ${{ github.event.issue.html_url }}
