name: LINE Notify Issues Opened
on:
  issues:
    types: opened
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            Issue is opened.
            📦 ${{ github.event.repository.name }}
            #${{ github.event.issue.number }} : ${{ github.event.issue.title }}
            ${{ github.event.issue.html_url }}